version: "3.8"

services:
  k6:
    build: .
    container_name: k6-performance-test
    env_file: .env
    volumes:
      - ./tests:/tests # Mount the tests directory
      - ./utils:/utils # Mount the utils directory (adjusted to be relative to the project root)
      - ./api:/api # Mount the api directory
      - ./config:/config # Mount the config directory
    command: sh ./runtest.sh
