version: "3.8"

services:
  k6:
    build: .
    container_name: k6-performance-test
    env_file: .env
    volumes:
      - ./tests:/app/tests # Mount the tests directory
      - ./utils:/app/utils # Mount the utils directory
      - ./api:/app/api # Mount the api directory
      - ./config:/app/config # Mount the config directory
    command: sh ./runtest.sh
